### ISSUE TITLE
Loop noclip

### ISSUE THREAD

**Issue by anartoast** [Moffein/Potmobile#2]
I know this mod is probally not being serious to itself as its... literally two survivors that do the same thing and they also are really, really fucking hard to controll.
If you are ever going to care about it, i would say to improve the movement as the only thing you do is press w as other buttons mess you up and add more damage to ram or something like that so you can oneshot bosses as the primary is not that reliable.

that being said, i really just wanted to say fuck you. i finished a run without skips, 80 min. i suffered more than jesus at this point.
good mod tho 6.5/10, very fun at the first 3 minutes.

**Comment by Moffein** [comment]
Improving the movement is beyond the scope of this mod, but I can buff the ram damage. I think Hauler is in a good state, so I guess I'll buff the Potmobile to use the same ram damage numbers as the Hauler. This'll allow it to hit higher ram damage than the Hauler due to its faster speed, but that should be fine since it's impossible to control.
